import './globals.css'

import type { FC, ReactNode } from 'react'

import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-BR" className={inter.variable}>
      <body className="bg-zinc-900 text-zinc-200">{children}</body>
    </html>
  )
}

export default RootLayout
